name: Echidna Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Installing dependencies
        run: npm install
      - name: Compile and create artifacts
        run: npm run compile
      - name: Run Echidna
        uses: crytic/echidna-action@v2.0.2
        with:
          solc-version: 0.8.17
          files: .
          contract: Registry
          crytic-args: --hardhat-ignore-compile
          format: text
